### ISSUE TITLE
[v3.X] Feature Roadmap

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#283]
This issue acts as a roadmap aggregating the features exclusively for the next version of this library.

Further development of Plotly.NET 3.x will be conducted on the `dev` branch, which will merge releases into `v2`

- [ ] Keep up with plot additions and bugfixes/ version increases in plotly.js (this can never be ticked, so see this more as a support/mission statement 😆)
- [x] Rewrite the C# compatibility layer as new project `Plotly.NET.CSharp` - *in C#* - this will get rid of many awkward hiccups between F# and C# constructs (which can be hidden internally) and drastically improve the usability of Plotly.NET from C#. (#285 )
- [ ] Incrementally add a C# documentation section using that layer.
