### ISSUE TITLE
[C#] Plotly.NET.CSharp Roadmap

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#379]
This issue tracks the roadmap for the native C# package Plotly.NET.CSharp

Plans on how to design and develop the C# API have been laid out and tracked in #285 and #322.

The general roadmap implementation-wise is the following:

- [x] 1. C# bindings for the high-level Chart construction API (#296), one binding per chart at first (no overloads)
- [ ] 2. C# GenericChart Extension methods (this covers more or less all styling functions). Once these are finished, the F# extension methods for fluent interface can be removed.
- [ ] 3. C# bindings for Object abstractions (TraceObjects, LayoutObjects, etc.) this might be a bit tricky
    Progress on this side has been made on the ['csharp-object-bindings' branch](https://github.com/plotly/Plotly.NET/tree/csharp-object-bindings/src/Plotly.NET.Codegen). In short, all these bindings can be auto-generated by using reflection on the F# objects. Might be worth to look into [C# source generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)

The way to go for the future is clearly code generation. The F# core API could in theory also created from the plotly.js JSON schema, but has many features that would be hard to automate such as type safety for enums etc.

To prevent having to namually maintain 2 code bases though, we should at least try to auto-generate the C# API based on the F# API, over which we have full control.
