### ISSUE TITLE
Roadmap for 2.0

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#43]
Features that are needed for 2.0 to be considered feature complete are tracked here. Feel free to add suggestions/issues.

- [x] Improve usablity from C#: ~#52~, #71 (we have to admit defeat and introduce a pure C# layer in 2.x +. F# constructs from C# are just awkward sometimes.)
- [x] Full Trace coverage (meaning full chart coverage): #42 
- [x] Coverage for most if not all Layout Objects/Properties: #44 
- [x] Improved markdown documentation for all Chart functions: #40 
- [x] Unit tests for the core functionality: #51
- [x] Improve dotnet interactive integration [See PR by @WalternativE](https://github.com/plotly/Plotly.NET/pull/54)
- [x] Add example dotnet interactive notebooks for docs
- [x] Add chart theme support: #14 
- [x] Add functionality to render charts as images: #21 
- [x] Use a dedicated color library
- [x] Move the project to .NET Core only (ditch the WPF project) (done: 40878d37f1499b3b6e14b5d3b816097bd6ea33ee)
- [x] Adapt the Chart type for better consumption across the plotly ecosystem (Dash, Kaleido, Plotly.js itself, etc.): #49 
- [x] Unify casing in ChartAPIs #105

**Comment by WhiteBlackGoose** [comment]
Add this to the list: https://github.com/plotly/Plotly.NET/issues/105

**Comment by kMutagene** [comment]
Feels good to be able to close this <3
